# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "videojoiner"
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Rafael Perez", "Luis Ciudad"]
  s.date = "2013-01-23"
  s.description = "This gem contains modules to create a single video file using a set of videos as input, via ffmpeg concat demuxer."
  s.email = ["rperez@nosolosoftware.biz", "lciudad@nosolosoftware.biz"]
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "features/create_joined_video.feature",
    "features/delete_joined_video.feature",
    "features/step_definitions/join_steps.rb",
    "features/support/env.rb",
    "features/support/hooks.rb",
    "features/support/incorrect.mp4",
    "features/support/sample.mp4",
    "lib/videojoiner.rb",
    "lib/videojoiner/ffmpeg/joiner_process.rb",
    "lib/videojoiner/joiner.rb",
    "videojoiner.gemspec"
  ]
  s.homepage = "https://projects.nosolosoftware.biz/mwengine/videojoiner"
  s.licenses = ["GPLv3"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Gem to join sets of video files into a single video file using ffmpeg"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<runnable>, ["~> 0.3.1"])
      s.add_runtime_dependency(%q<wait_for>, ["~> 0.1.1"])
      s.add_runtime_dependency(%q<activesupport>, ["~> 3.2.8"])
      s.add_development_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<cucumber>, [">= 1.2.1"])
      s.add_development_dependency(%q<bundler>, ["~> 1.2.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<fattr>, [">= 0"])
      s.add_development_dependency(%q<arrayfields>, [">= 0"])
      s.add_development_dependency(%q<simplecov>, ["~> 0.6.4"])
      s.add_development_dependency(%q<map>, ["= 4.7.1"])
      s.add_development_dependency(%q<churn>, ["~> 0.0.19"])
      s.add_development_dependency(%q<chronic>, ["= 0.3.0"])
      s.add_development_dependency(%q<metrical>, ["~> 0.1.0"])
      s.add_development_dependency(%q<rvideo>, ["~> 0.9.3"])
    else
      s.add_dependency(%q<runnable>, ["~> 0.3.1"])
      s.add_dependency(%q<wait_for>, ["~> 0.1.1"])
      s.add_dependency(%q<activesupport>, ["~> 3.2.8"])
      s.add_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<cucumber>, [">= 1.2.1"])
      s.add_dependency(%q<bundler>, ["~> 1.2.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<fattr>, [">= 0"])
      s.add_dependency(%q<arrayfields>, [">= 0"])
      s.add_dependency(%q<simplecov>, ["~> 0.6.4"])
      s.add_dependency(%q<map>, ["= 4.7.1"])
      s.add_dependency(%q<churn>, ["~> 0.0.19"])
      s.add_dependency(%q<chronic>, ["= 0.3.0"])
      s.add_dependency(%q<metrical>, ["~> 0.1.0"])
      s.add_dependency(%q<rvideo>, ["~> 0.9.3"])
    end
  else
    s.add_dependency(%q<runnable>, ["~> 0.3.1"])
    s.add_dependency(%q<wait_for>, ["~> 0.1.1"])
    s.add_dependency(%q<activesupport>, ["~> 3.2.8"])
    s.add_dependency(%q<rspec>, ["~> 2.8.0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<cucumber>, [">= 1.2.1"])
    s.add_dependency(%q<bundler>, ["~> 1.2.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<fattr>, [">= 0"])
    s.add_dependency(%q<arrayfields>, [">= 0"])
    s.add_dependency(%q<simplecov>, ["~> 0.6.4"])
    s.add_dependency(%q<map>, ["= 4.7.1"])
    s.add_dependency(%q<churn>, ["~> 0.0.19"])
    s.add_dependency(%q<chronic>, ["= 0.3.0"])
    s.add_dependency(%q<metrical>, ["~> 0.1.0"])
    s.add_dependency(%q<rvideo>, ["~> 0.9.3"])
  end
end

